Resources:
  ElasticIPLambdaSecurityGroup55086008:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: This is a security group for a vpc attached lambda that uses elastic ip to have outbound communication without the need for a NAT solution
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-c44e4dbe
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Elastic-IP-Lambda-Security-Group/Resource
  LambdaWithElasticIPServiceRole11989EB4:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Lambda-With-Elastic-IP/ServiceRole/Resource
  LambdaWithElasticIPA8DE7E3F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-199150394284-us-east-1
        S3Key: bf9a8fa66deb1e2866a36484a3e7cac2176ed16560e71a5b47ff604e05889c01.zip
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - LambdaWithElasticIPServiceRole11989EB4
          - Arn
      Runtime: nodejs18.x
      Timeout: 10
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt:
              - ElasticIPLambdaSecurityGroup55086008
              - GroupId
        SubnetIds:
          - subnet-296ceb64
    DependsOn:
      - LambdaWithElasticIPServiceRole11989EB4
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Lambda-With-Elastic-IP/Resource
      aws:asset:path: C:\Users\Mohamad.Soufan\Adesa-Laptop\AWS\Soufan AWS Company\serverless-patterns\lambda-elastic-ip-no-nat-gateway-cdk\cdk\cdk.out\asset.bf9a8fa66deb1e2866a36484a3e7cac2176ed16560e71a5b47ff604e05889c01
      aws:asset:is-bundled: true
      aws:asset:property: Code
  LambdaElasticIp:
    Type: AWS::EC2::EIP
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Lambda-Elastic-Ip
  AssociateElasticIPCRServiceRole10A2D9BC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Associate-Elastic-IP-CR/ServiceRole/Resource
  AssociateElasticIPCRServiceRoleDefaultPolicyD84881C7:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ec2:AssociateAddress
              - ec2:DescribeNetworkInterfaces
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: AssociateElasticIPCRServiceRoleDefaultPolicyD84881C7
      Roles:
        - Ref: AssociateElasticIPCRServiceRole10A2D9BC
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Associate-Elastic-IP-CR/ServiceRole/DefaultPolicy/Resource
  AssociateElasticIPCR7F3F6FA0:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-199150394284-us-east-1
        S3Key: 96ad91aa137da1055325e8b40c71a3f43bad05b5ff16c67e56eb6dfad54f2644.zip
      Environment:
        Variables:
          ELASTIC_IP_ALLOCATION_ID:
            Fn::GetAtt:
              - LambdaElasticIp
              - AllocationId
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - AssociateElasticIPCRServiceRole10A2D9BC
          - Arn
      Runtime: nodejs18.x
      Timeout: 10
    DependsOn:
      - AssociateElasticIPCRServiceRoleDefaultPolicyD84881C7
      - AssociateElasticIPCRServiceRole10A2D9BC
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Associate-Elastic-IP-CR/Resource
      aws:asset:path: C:\Users\Mohamad.Soufan\Adesa-Laptop\AWS\Soufan AWS Company\serverless-patterns\lambda-elastic-ip-no-nat-gateway-cdk\cdk\cdk.out\asset.96ad91aa137da1055325e8b40c71a3f43bad05b5ff16c67e56eb6dfad54f2644
      aws:asset:is-bundled: true
      aws:asset:property: Code
  InvokeAssociateElasticIPLambda3C1584F9:
    Type: Custom::AWS
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd22872D164C4C
          - Arn
      Create:
        Fn::Join:
          - ""
          - - '{"service":"Lambda","action":"invoke","parameters":{"FunctionName":"'
            - Ref: AssociateElasticIPCR7F3F6FA0
            - '","Payload":"{\"vpcId\":\"vpc-c44e4dbe\",\"subnetId\":\"subnet-296ceb64\",\"securityGroupId\":\"'
            - Fn::GetAtt:
                - ElasticIPLambdaSecurityGroup55086008
                - GroupId
            - \",\"availabilityZone\":\"us-east-1a\",\"allocationId\":\"
            - Fn::GetAtt:
                - LambdaElasticIp
                - AllocationId
            - \",\"staticIp\":\"
            - Ref: LambdaElasticIp
            - \",\"functionName\":\"
            - Ref: LambdaWithElasticIPA8DE7E3F
            - \",\"date\":\"2023-09-07T20:06:32.365Z\"}"},"physicalResourceId":{"id":"Associate-Elastic-IP-CR"}}
      Update:
        Fn::Join:
          - ""
          - - '{"service":"Lambda","action":"invoke","parameters":{"FunctionName":"'
            - Ref: AssociateElasticIPCR7F3F6FA0
            - '","Payload":"{\"vpcId\":\"vpc-c44e4dbe\",\"subnetId\":\"subnet-296ceb64\",\"securityGroupId\":\"'
            - Fn::GetAtt:
                - ElasticIPLambdaSecurityGroup55086008
                - GroupId
            - \",\"availabilityZone\":\"us-east-1a\",\"allocationId\":\"
            - Fn::GetAtt:
                - LambdaElasticIp
                - AllocationId
            - \",\"staticIp\":\"
            - Ref: LambdaElasticIp
            - \",\"functionName\":\"
            - Ref: LambdaWithElasticIPA8DE7E3F
            - \",\"date\":\"2023-09-07T20:06:32.365Z\"}"},"physicalResourceId":{"id":"Associate-Elastic-IP-CR"}}
      InstallLatestAwsSdk: false
    DependsOn:
      - InvokeAssociateElasticIPLambdaCustomResourcePolicy9687F247
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Invoke-Associate-Elastic-IP-Lambda/Resource/Default
  InvokeAssociateElasticIPLambdaCustomResourcePolicy9687F247:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:Invoke
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: InvokeAssociateElasticIPLambdaCustomResourcePolicy9687F247
      Roles:
        - Ref: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/Invoke-Associate-Elastic-IP-Lambda/CustomResourcePolicy/Resource
  AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/AWS679f53fac002430cb0da5b7982bd2287/ServiceRole/Resource
  AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - AssociateElasticIPCR7F3F6FA0
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - AssociateElasticIPCR7F3F6FA0
                        - Arn
                    - :*
        Version: "2012-10-17"
      PolicyName: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E
      Roles:
        - Ref: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/AWS679f53fac002430cb0da5b7982bd2287/ServiceRole/DefaultPolicy/Resource
  AWS679f53fac002430cb0da5b7982bd22872D164C4C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-199150394284-us-east-1
        S3Key: ba5407117985fa148f61d8537da4904529e5c8264aed5d840f0a26700b5471fc.zip
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
          - Arn
      Runtime: nodejs18.x
      Timeout: 120
    DependsOn:
      - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleDefaultPolicyD28E1A5E
      - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/AWS679f53fac002430cb0da5b7982bd2287/Resource
      aws:asset:path: C:\Users\Mohamad.Soufan\Adesa-Laptop\AWS\Soufan AWS Company\serverless-patterns\lambda-elastic-ip-no-nat-gateway-cdk\cdk\node_modules\aws-cdk-lib\custom-resources\lib\aws-custom-resource\runtime
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2VPTW/CMAz9LdxTb2UctuNAbOIyofIDquB6yG2aoDgZQlX++9LSMWk7vQ87z3lLeFnB40JfpMCmKwwfYTgEjZ2qSFz0SCrP6oFwmQeE0XO4vnsXz2rzaf8Z290+KaP7Y6Nr6xpqBT4meIsWAzurWPcwVM7QuD7h3hnG6yhvLCl5qrUIBYHXEbKGdcSOwloLzfEw5Af31APbk6Hgfp0fkpKaQnKpU15SGCW4vvZzu3ziIpvJuxf+K/M/Z57UWApaefgqn6FcQblohbnw0QbuCaobfgOBC1wBVQEAAA==
    Metadata:
      aws:cdk:path: LambdaElasticIpStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

